name: CI
on:
    push: 
      branches: [master]
    pull_request:
      branches: [master]

jobs:
    linter:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Lint Code Base
              uses: github/super-linter@v4

    scan_secure:
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep
        if: (github.actor != 'dependabot[bot]')
        steps: 
            - uses: actions/checkout@v3
            - name: semgrep
              run: semgrep --config auto 
